package com.yougy.home.bean;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Lines.proto

public final class LinesProto {
  private LinesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PointOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Point)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required float x = 1;</code>
     */
    boolean hasX();
    /**
     * <code>required float x = 1;</code>
     */
    float getX();

    /**
     * <code>required float y = 2;</code>
     */
    boolean hasY();
    /**
     * <code>required float y = 2;</code>
     */
    float getY();
  }
  /**
   * Protobuf type {@code Point}
   */
  public  static final class Point extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Point)
      PointOrBuilder {
    // Use Point.newBuilder() to construct.
    private Point(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Point() {
      x_ = 0F;
      y_ = 0F;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Point(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              x_ = input.readFloat();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              y_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LinesProto.internal_static_Point_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LinesProto.internal_static_Point_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Point.class, Builder.class);
    }

    private int bitField0_;
    public static final int X_FIELD_NUMBER = 1;
    private float x_;
    /**
     * <code>required float x = 1;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float x = 1;</code>
     */
    public float getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private float y_;
    /**
     * <code>required float y = 2;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float y = 2;</code>
     */
    public float getY() {
      return y_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, y_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, y_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Point)) {
        return super.equals(obj);
      }
      Point other = (Point) obj;

      boolean result = true;
      result = result && (hasX() == other.hasX());
      if (hasX()) {
        result = result && (
            Float.floatToIntBits(getX())
            == Float.floatToIntBits(
                other.getX()));
      }
      result = result && (hasY() == other.hasY());
      if (hasY()) {
        result = result && (
            Float.floatToIntBits(getY())
            == Float.floatToIntBits(
                other.getY()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasX()) {
        hash = (37 * hash) + X_FIELD_NUMBER;
        hash = (53 * hash) + Float.floatToIntBits(
            getX());
      }
      if (hasY()) {
        hash = (37 * hash) + Y_FIELD_NUMBER;
        hash = (53 * hash) + Float.floatToIntBits(
            getY());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Point parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Point parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Point parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Point parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Point parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Point parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Point parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Point parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Point parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Point parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Point prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Point}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Point)
        PointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LinesProto.internal_static_Point_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LinesProto.internal_static_Point_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Point.class, Builder.class);
      }

      // Construct using LinesProto.Point.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        x_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LinesProto.internal_static_Point_descriptor;
      }

      public Point getDefaultInstanceForType() {
        return Point.getDefaultInstance();
      }

      public Point build() {
        Point result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Point buildPartial() {
        Point result = new Point(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Point) {
          return mergeFrom((Point)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Point other) {
        if (other == Point.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasX()) {
          return false;
        }
          return hasY();
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Point parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Point) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float x_ ;
      /**
       * <code>required float x = 1;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required float x = 1;</code>
       */
      public float getX() {
        return x_;
      }
      /**
       * <code>required float x = 1;</code>
       */
      public Builder setX(float value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float x = 1;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0F;
        onChanged();
        return this;
      }

      private float y_ ;
      /**
       * <code>required float y = 2;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float y = 2;</code>
       */
      public float getY() {
        return y_;
      }
      /**
       * <code>required float y = 2;</code>
       */
      public Builder setY(float value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float y = 2;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Point)
    }

    // @@protoc_insertion_point(class_scope:Point)
    private static final Point DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Point();
    }

    public static Point getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Point>
        PARSER = new com.google.protobuf.AbstractParser<Point>() {
      public Point parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Point(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Point> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Point> getParserForType() {
      return PARSER;
    }

    public Point getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LineOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Line)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required float width = 1;</code>
     */
    boolean hasWidth();
    /**
     * <code>required float width = 1;</code>
     */
    float getWidth();

    /**
     * <code>required .Point start = 2;</code>
     */
    boolean hasStart();
    /**
     * <code>required .Point start = 2;</code>
     */
    Point getStart();
    /**
     * <code>required .Point start = 2;</code>
     */
    PointOrBuilder getStartOrBuilder();

    /**
     * <code>repeated .Point point = 3;</code>
     */
    java.util.List<Point>
        getPointList();
    /**
     * <code>repeated .Point point = 3;</code>
     */
    Point getPoint(int index);
    /**
     * <code>repeated .Point point = 3;</code>
     */
    int getPointCount();
    /**
     * <code>repeated .Point point = 3;</code>
     */
    java.util.List<? extends PointOrBuilder>
        getPointOrBuilderList();
    /**
     * <code>repeated .Point point = 3;</code>
     */
    PointOrBuilder getPointOrBuilder(
            int index);

    /**
     * <code>required .Point end = 4;</code>
     */
    boolean hasEnd();
    /**
     * <code>required .Point end = 4;</code>
     */
    Point getEnd();
    /**
     * <code>required .Point end = 4;</code>
     */
    PointOrBuilder getEndOrBuilder();

    /**
     * <code>required int32 color = 5;</code>
     */
    boolean hasColor();
    /**
     * <code>required int32 color = 5;</code>
     */
    int getColor();

    /**
     * <code>required int32 type = 6;</code>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 6;</code>
     */
    int getType();
  }
  /**
   * Protobuf type {@code Line}
   */
  public  static final class Line extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Line)
      LineOrBuilder {
    // Use Line.newBuilder() to construct.
    private Line(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Line() {
      width_ = 0F;
      point_ = java.util.Collections.emptyList();
      color_ = 0;
      type_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Line(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              width_ = input.readFloat();
              break;
            }
            case 18: {
              Point.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = start_.toBuilder();
              }
              start_ = input.readMessage(Point.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(start_);
                start_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                point_ = new java.util.ArrayList<Point>();
                mutable_bitField0_ |= 0x00000004;
              }
              point_.add(
                  input.readMessage(Point.PARSER, extensionRegistry));
              break;
            }
            case 34: {
              Point.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = end_.toBuilder();
              }
              end_ = input.readMessage(Point.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(end_);
                end_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000008;
              color_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000010;
              type_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          point_ = java.util.Collections.unmodifiableList(point_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LinesProto.internal_static_Line_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LinesProto.internal_static_Line_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Line.class, Builder.class);
    }

    private int bitField0_;
    public static final int WIDTH_FIELD_NUMBER = 1;
    private float width_;
    /**
     * <code>required float width = 1;</code>
     */
    public boolean hasWidth() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float width = 1;</code>
     */
    public float getWidth() {
      return width_;
    }

    public static final int START_FIELD_NUMBER = 2;
    private Point start_;
    /**
     * <code>required .Point start = 2;</code>
     */
    public boolean hasStart() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .Point start = 2;</code>
     */
    public Point getStart() {
      return start_ == null ? Point.getDefaultInstance() : start_;
    }
    /**
     * <code>required .Point start = 2;</code>
     */
    public PointOrBuilder getStartOrBuilder() {
      return start_ == null ? Point.getDefaultInstance() : start_;
    }

    public static final int POINT_FIELD_NUMBER = 3;
    private java.util.List<Point> point_;
    /**
     * <code>repeated .Point point = 3;</code>
     */
    public java.util.List<Point> getPointList() {
      return point_;
    }
    /**
     * <code>repeated .Point point = 3;</code>
     */
    public java.util.List<? extends PointOrBuilder>
        getPointOrBuilderList() {
      return point_;
    }
    /**
     * <code>repeated .Point point = 3;</code>
     */
    public int getPointCount() {
      return point_.size();
    }
    /**
     * <code>repeated .Point point = 3;</code>
     */
    public Point getPoint(int index) {
      return point_.get(index);
    }
    /**
     * <code>repeated .Point point = 3;</code>
     */
    public PointOrBuilder getPointOrBuilder(
        int index) {
      return point_.get(index);
    }

    public static final int END_FIELD_NUMBER = 4;
    private Point end_;
    /**
     * <code>required .Point end = 4;</code>
     */
    public boolean hasEnd() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .Point end = 4;</code>
     */
    public Point getEnd() {
      return end_ == null ? Point.getDefaultInstance() : end_;
    }
    /**
     * <code>required .Point end = 4;</code>
     */
    public PointOrBuilder getEndOrBuilder() {
      return end_ == null ? Point.getDefaultInstance() : end_;
    }

    public static final int COLOR_FIELD_NUMBER = 5;
    private int color_;
    /**
     * <code>required int32 color = 5;</code>
     */
    public boolean hasColor() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 color = 5;</code>
     */
    public int getColor() {
      return color_;
    }

    public static final int TYPE_FIELD_NUMBER = 6;
    private int type_;
    /**
     * <code>required int32 type = 6;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 type = 6;</code>
     */
    public int getType() {
      return type_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasWidth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStart()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEnd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasColor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getStart().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPointCount(); i++) {
        if (!getPoint(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (!getEnd().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, width_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getStart());
      }
      for (int i = 0; i < point_.size(); i++) {
        output.writeMessage(3, point_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(4, getEnd());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(5, color_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(6, type_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, width_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getStart());
      }
      for (int i = 0; i < point_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, point_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getEnd());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, color_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Line)) {
        return super.equals(obj);
      }
      Line other = (Line) obj;

      boolean result = true;
      result = result && (hasWidth() == other.hasWidth());
      if (hasWidth()) {
        result = result && (
            Float.floatToIntBits(getWidth())
            == Float.floatToIntBits(
                other.getWidth()));
      }
      result = result && (hasStart() == other.hasStart());
      if (hasStart()) {
        result = result && getStart()
            .equals(other.getStart());
      }
      result = result && getPointList()
          .equals(other.getPointList());
      result = result && (hasEnd() == other.hasEnd());
      if (hasEnd()) {
        result = result && getEnd()
            .equals(other.getEnd());
      }
      result = result && (hasColor() == other.hasColor());
      if (hasColor()) {
        result = result && (getColor()
            == other.getColor());
      }
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && (getType()
            == other.getType());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasWidth()) {
        hash = (37 * hash) + WIDTH_FIELD_NUMBER;
        hash = (53 * hash) + Float.floatToIntBits(
            getWidth());
      }
      if (hasStart()) {
        hash = (37 * hash) + START_FIELD_NUMBER;
        hash = (53 * hash) + getStart().hashCode();
      }
      if (getPointCount() > 0) {
        hash = (37 * hash) + POINT_FIELD_NUMBER;
        hash = (53 * hash) + getPointList().hashCode();
      }
      if (hasEnd()) {
        hash = (37 * hash) + END_FIELD_NUMBER;
        hash = (53 * hash) + getEnd().hashCode();
      }
      if (hasColor()) {
        hash = (37 * hash) + COLOR_FIELD_NUMBER;
        hash = (53 * hash) + getColor();
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Line parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Line parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Line parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Line parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Line parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Line parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Line parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Line parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Line parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Line parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Line prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Line}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Line)
        LineOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LinesProto.internal_static_Line_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LinesProto.internal_static_Line_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Line.class, Builder.class);
      }

      // Construct using LinesProto.Line.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getStartFieldBuilder();
          getPointFieldBuilder();
          getEndFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        width_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (startBuilder_ == null) {
          start_ = null;
        } else {
          startBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (pointBuilder_ == null) {
          point_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          pointBuilder_.clear();
        }
        if (endBuilder_ == null) {
          end_ = null;
        } else {
          endBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        color_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LinesProto.internal_static_Line_descriptor;
      }

      public Line getDefaultInstanceForType() {
        return Line.getDefaultInstance();
      }

      public Line build() {
        Line result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Line buildPartial() {
        Line result = new Line(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.width_ = width_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (startBuilder_ == null) {
          result.start_ = start_;
        } else {
          result.start_ = startBuilder_.build();
        }
        if (pointBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            point_ = java.util.Collections.unmodifiableList(point_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.point_ = point_;
        } else {
          result.point_ = pointBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        if (endBuilder_ == null) {
          result.end_ = end_;
        } else {
          result.end_ = endBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.color_ = color_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Line) {
          return mergeFrom((Line)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Line other) {
        if (other == Line.getDefaultInstance()) return this;
        if (other.hasWidth()) {
          setWidth(other.getWidth());
        }
        if (other.hasStart()) {
          mergeStart(other.getStart());
        }
        if (pointBuilder_ == null) {
          if (!other.point_.isEmpty()) {
            if (point_.isEmpty()) {
              point_ = other.point_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensurePointIsMutable();
              point_.addAll(other.point_);
            }
            onChanged();
          }
        } else {
          if (!other.point_.isEmpty()) {
            if (pointBuilder_.isEmpty()) {
              pointBuilder_.dispose();
              pointBuilder_ = null;
              point_ = other.point_;
              bitField0_ = (bitField0_ & ~0x00000004);
              pointBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPointFieldBuilder() : null;
            } else {
              pointBuilder_.addAllMessages(other.point_);
            }
          }
        }
        if (other.hasEnd()) {
          mergeEnd(other.getEnd());
        }
        if (other.hasColor()) {
          setColor(other.getColor());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasWidth()) {
          return false;
        }
        if (!hasStart()) {
          return false;
        }
        if (!hasEnd()) {
          return false;
        }
        if (!hasColor()) {
          return false;
        }
        if (!hasType()) {
          return false;
        }
        if (!getStart().isInitialized()) {
          return false;
        }
        for (int i = 0; i < getPointCount(); i++) {
          if (!getPoint(i).isInitialized()) {
            return false;
          }
        }
          return getEnd().isInitialized();
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Line parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Line) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float width_ ;
      /**
       * <code>required float width = 1;</code>
       */
      public boolean hasWidth() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required float width = 1;</code>
       */
      public float getWidth() {
        return width_;
      }
      /**
       * <code>required float width = 1;</code>
       */
      public Builder setWidth(float value) {
        bitField0_ |= 0x00000001;
        width_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float width = 1;</code>
       */
      public Builder clearWidth() {
        bitField0_ = (bitField0_ & ~0x00000001);
        width_ = 0F;
        onChanged();
        return this;
      }

      private Point start_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          Point, Point.Builder, PointOrBuilder> startBuilder_;
      /**
       * <code>required .Point start = 2;</code>
       */
      public boolean hasStart() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .Point start = 2;</code>
       */
      public Point getStart() {
        if (startBuilder_ == null) {
          return start_ == null ? Point.getDefaultInstance() : start_;
        } else {
          return startBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Point start = 2;</code>
       */
      public Builder setStart(Point value) {
        if (startBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          start_ = value;
          onChanged();
        } else {
          startBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Point start = 2;</code>
       */
      public Builder setStart(
          Point.Builder builderForValue) {
        if (startBuilder_ == null) {
          start_ = builderForValue.build();
          onChanged();
        } else {
          startBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Point start = 2;</code>
       */
      public Builder mergeStart(Point value) {
        if (startBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              start_ != null &&
              start_ != Point.getDefaultInstance()) {
            start_ =
              Point.newBuilder(start_).mergeFrom(value).buildPartial();
          } else {
            start_ = value;
          }
          onChanged();
        } else {
          startBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Point start = 2;</code>
       */
      public Builder clearStart() {
        if (startBuilder_ == null) {
          start_ = null;
          onChanged();
        } else {
          startBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .Point start = 2;</code>
       */
      public Point.Builder getStartBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getStartFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Point start = 2;</code>
       */
      public PointOrBuilder getStartOrBuilder() {
        if (startBuilder_ != null) {
          return startBuilder_.getMessageOrBuilder();
        } else {
          return start_ == null ?
              Point.getDefaultInstance() : start_;
        }
      }
      /**
       * <code>required .Point start = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Point, Point.Builder, PointOrBuilder>
          getStartFieldBuilder() {
        if (startBuilder_ == null) {
          startBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Point, Point.Builder, PointOrBuilder>(
                  getStart(),
                  getParentForChildren(),
                  isClean());
          start_ = null;
        }
        return startBuilder_;
      }

      private java.util.List<Point> point_ =
        java.util.Collections.emptyList();
      private void ensurePointIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          point_ = new java.util.ArrayList<Point>(point_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Point, Point.Builder, PointOrBuilder> pointBuilder_;

      /**
       * <code>repeated .Point point = 3;</code>
       */
      public java.util.List<Point> getPointList() {
        if (pointBuilder_ == null) {
          return java.util.Collections.unmodifiableList(point_);
        } else {
          return pointBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Point point = 3;</code>
       */
      public int getPointCount() {
        if (pointBuilder_ == null) {
          return point_.size();
        } else {
          return pointBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Point point = 3;</code>
       */
      public Point getPoint(int index) {
        if (pointBuilder_ == null) {
          return point_.get(index);
        } else {
          return pointBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Point point = 3;</code>
       */
      public Builder setPoint(
          int index, Point value) {
        if (pointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointIsMutable();
          point_.set(index, value);
          onChanged();
        } else {
          pointBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Point point = 3;</code>
       */
      public Builder setPoint(
          int index, Point.Builder builderForValue) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.set(index, builderForValue.build());
          onChanged();
        } else {
          pointBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Point point = 3;</code>
       */
      public Builder addPoint(Point value) {
        if (pointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointIsMutable();
          point_.add(value);
          onChanged();
        } else {
          pointBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Point point = 3;</code>
       */
      public Builder addPoint(
          int index, Point value) {
        if (pointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePointIsMutable();
          point_.add(index, value);
          onChanged();
        } else {
          pointBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Point point = 3;</code>
       */
      public Builder addPoint(
          Point.Builder builderForValue) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.add(builderForValue.build());
          onChanged();
        } else {
          pointBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Point point = 3;</code>
       */
      public Builder addPoint(
          int index, Point.Builder builderForValue) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.add(index, builderForValue.build());
          onChanged();
        } else {
          pointBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Point point = 3;</code>
       */
      public Builder addAllPoint(
          Iterable<? extends Point> values) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, point_);
          onChanged();
        } else {
          pointBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Point point = 3;</code>
       */
      public Builder clearPoint() {
        if (pointBuilder_ == null) {
          point_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          pointBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Point point = 3;</code>
       */
      public Builder removePoint(int index) {
        if (pointBuilder_ == null) {
          ensurePointIsMutable();
          point_.remove(index);
          onChanged();
        } else {
          pointBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Point point = 3;</code>
       */
      public Point.Builder getPointBuilder(
          int index) {
        return getPointFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Point point = 3;</code>
       */
      public PointOrBuilder getPointOrBuilder(
          int index) {
        if (pointBuilder_ == null) {
          return point_.get(index);  } else {
          return pointBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Point point = 3;</code>
       */
      public java.util.List<? extends PointOrBuilder>
           getPointOrBuilderList() {
        if (pointBuilder_ != null) {
          return pointBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(point_);
        }
      }
      /**
       * <code>repeated .Point point = 3;</code>
       */
      public Point.Builder addPointBuilder() {
        return getPointFieldBuilder().addBuilder(
            Point.getDefaultInstance());
      }
      /**
       * <code>repeated .Point point = 3;</code>
       */
      public Point.Builder addPointBuilder(
          int index) {
        return getPointFieldBuilder().addBuilder(
            index, Point.getDefaultInstance());
      }
      /**
       * <code>repeated .Point point = 3;</code>
       */
      public java.util.List<Point.Builder>
           getPointBuilderList() {
        return getPointFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Point, Point.Builder, PointOrBuilder>
          getPointFieldBuilder() {
        if (pointBuilder_ == null) {
          pointBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Point, Point.Builder, PointOrBuilder>(
                  point_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          point_ = null;
        }
        return pointBuilder_;
      }

      private Point end_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          Point, Point.Builder, PointOrBuilder> endBuilder_;
      /**
       * <code>required .Point end = 4;</code>
       */
      public boolean hasEnd() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .Point end = 4;</code>
       */
      public Point getEnd() {
        if (endBuilder_ == null) {
          return end_ == null ? Point.getDefaultInstance() : end_;
        } else {
          return endBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Point end = 4;</code>
       */
      public Builder setEnd(Point value) {
        if (endBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          end_ = value;
          onChanged();
        } else {
          endBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .Point end = 4;</code>
       */
      public Builder setEnd(
          Point.Builder builderForValue) {
        if (endBuilder_ == null) {
          end_ = builderForValue.build();
          onChanged();
        } else {
          endBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .Point end = 4;</code>
       */
      public Builder mergeEnd(Point value) {
        if (endBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              end_ != null &&
              end_ != Point.getDefaultInstance()) {
            end_ =
              Point.newBuilder(end_).mergeFrom(value).buildPartial();
          } else {
            end_ = value;
          }
          onChanged();
        } else {
          endBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .Point end = 4;</code>
       */
      public Builder clearEnd() {
        if (endBuilder_ == null) {
          end_ = null;
          onChanged();
        } else {
          endBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>required .Point end = 4;</code>
       */
      public Point.Builder getEndBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getEndFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Point end = 4;</code>
       */
      public PointOrBuilder getEndOrBuilder() {
        if (endBuilder_ != null) {
          return endBuilder_.getMessageOrBuilder();
        } else {
          return end_ == null ?
              Point.getDefaultInstance() : end_;
        }
      }
      /**
       * <code>required .Point end = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Point, Point.Builder, PointOrBuilder>
          getEndFieldBuilder() {
        if (endBuilder_ == null) {
          endBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Point, Point.Builder, PointOrBuilder>(
                  getEnd(),
                  getParentForChildren(),
                  isClean());
          end_ = null;
        }
        return endBuilder_;
      }

      private int color_ ;
      /**
       * <code>required int32 color = 5;</code>
       */
      public boolean hasColor() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 color = 5;</code>
       */
      public int getColor() {
        return color_;
      }
      /**
       * <code>required int32 color = 5;</code>
       */
      public Builder setColor(int value) {
        bitField0_ |= 0x00000010;
        color_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 color = 5;</code>
       */
      public Builder clearColor() {
        bitField0_ = (bitField0_ & ~0x00000010);
        color_ = 0;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>required int32 type = 6;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 type = 6;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 6;</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000020;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 6;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        type_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Line)
    }

    // @@protoc_insertion_point(class_scope:Line)
    private static final Line DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Line();
    }

    public static Line getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Line>
        PARSER = new com.google.protobuf.AbstractParser<Line>() {
      public Line parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Line(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Line> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Line> getParserForType() {
      return PARSER;
    }

    public Line getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LinesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Lines)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Line line = 1;</code>
     */
    java.util.List<Line>
        getLineList();
    /**
     * <code>repeated .Line line = 1;</code>
     */
    Line getLine(int index);
    /**
     * <code>repeated .Line line = 1;</code>
     */
    int getLineCount();
    /**
     * <code>repeated .Line line = 1;</code>
     */
    java.util.List<? extends LineOrBuilder>
        getLineOrBuilderList();
    /**
     * <code>repeated .Line line = 1;</code>
     */
    LineOrBuilder getLineOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code Lines}
   */
  public  static final class Lines extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Lines)
      LinesOrBuilder {
    // Use Lines.newBuilder() to construct.
    private Lines(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Lines() {
      line_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Lines(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                line_ = new java.util.ArrayList<Line>();
                mutable_bitField0_ |= 0x00000001;
              }
              line_.add(
                  input.readMessage(Line.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          line_ = java.util.Collections.unmodifiableList(line_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LinesProto.internal_static_Lines_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LinesProto.internal_static_Lines_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Lines.class, Builder.class);
    }

    public static final int LINE_FIELD_NUMBER = 1;
    private java.util.List<Line> line_;
    /**
     * <code>repeated .Line line = 1;</code>
     */
    public java.util.List<Line> getLineList() {
      return line_;
    }
    /**
     * <code>repeated .Line line = 1;</code>
     */
    public java.util.List<? extends LineOrBuilder>
        getLineOrBuilderList() {
      return line_;
    }
    /**
     * <code>repeated .Line line = 1;</code>
     */
    public int getLineCount() {
      return line_.size();
    }
    /**
     * <code>repeated .Line line = 1;</code>
     */
    public Line getLine(int index) {
      return line_.get(index);
    }
    /**
     * <code>repeated .Line line = 1;</code>
     */
    public LineOrBuilder getLineOrBuilder(
        int index) {
      return line_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getLineCount(); i++) {
        if (!getLine(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < line_.size(); i++) {
        output.writeMessage(1, line_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < line_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, line_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Lines)) {
        return super.equals(obj);
      }
      Lines other = (Lines) obj;

      boolean result = true;
      result = result && getLineList()
          .equals(other.getLineList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getLineCount() > 0) {
        hash = (37 * hash) + LINE_FIELD_NUMBER;
        hash = (53 * hash) + getLineList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Lines parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Lines parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Lines parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Lines parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Lines parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Lines parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Lines parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Lines parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Lines parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Lines parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Lines prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Lines}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Lines)
        LinesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LinesProto.internal_static_Lines_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LinesProto.internal_static_Lines_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Lines.class, Builder.class);
      }

      // Construct using LinesProto.Lines.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLineFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (lineBuilder_ == null) {
          line_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          lineBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LinesProto.internal_static_Lines_descriptor;
      }

      public Lines getDefaultInstanceForType() {
        return Lines.getDefaultInstance();
      }

      public Lines build() {
        Lines result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Lines buildPartial() {
        Lines result = new Lines(this);
        int from_bitField0_ = bitField0_;
        if (lineBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            line_ = java.util.Collections.unmodifiableList(line_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.line_ = line_;
        } else {
          result.line_ = lineBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Lines) {
          return mergeFrom((Lines)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Lines other) {
        if (other == Lines.getDefaultInstance()) return this;
        if (lineBuilder_ == null) {
          if (!other.line_.isEmpty()) {
            if (line_.isEmpty()) {
              line_ = other.line_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureLineIsMutable();
              line_.addAll(other.line_);
            }
            onChanged();
          }
        } else {
          if (!other.line_.isEmpty()) {
            if (lineBuilder_.isEmpty()) {
              lineBuilder_.dispose();
              lineBuilder_ = null;
              line_ = other.line_;
              bitField0_ = (bitField0_ & ~0x00000001);
              lineBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLineFieldBuilder() : null;
            } else {
              lineBuilder_.addAllMessages(other.line_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getLineCount(); i++) {
          if (!getLine(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Lines parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Lines) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Line> line_ =
        java.util.Collections.emptyList();
      private void ensureLineIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          line_ = new java.util.ArrayList<Line>(line_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Line, Line.Builder, LineOrBuilder> lineBuilder_;

      /**
       * <code>repeated .Line line = 1;</code>
       */
      public java.util.List<Line> getLineList() {
        if (lineBuilder_ == null) {
          return java.util.Collections.unmodifiableList(line_);
        } else {
          return lineBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Line line = 1;</code>
       */
      public int getLineCount() {
        if (lineBuilder_ == null) {
          return line_.size();
        } else {
          return lineBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Line line = 1;</code>
       */
      public Line getLine(int index) {
        if (lineBuilder_ == null) {
          return line_.get(index);
        } else {
          return lineBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Line line = 1;</code>
       */
      public Builder setLine(
          int index, Line value) {
        if (lineBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLineIsMutable();
          line_.set(index, value);
          onChanged();
        } else {
          lineBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Line line = 1;</code>
       */
      public Builder setLine(
          int index, Line.Builder builderForValue) {
        if (lineBuilder_ == null) {
          ensureLineIsMutable();
          line_.set(index, builderForValue.build());
          onChanged();
        } else {
          lineBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Line line = 1;</code>
       */
      public Builder addLine(Line value) {
        if (lineBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLineIsMutable();
          line_.add(value);
          onChanged();
        } else {
          lineBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Line line = 1;</code>
       */
      public Builder addLine(
          int index, Line value) {
        if (lineBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLineIsMutable();
          line_.add(index, value);
          onChanged();
        } else {
          lineBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Line line = 1;</code>
       */
      public Builder addLine(
          Line.Builder builderForValue) {
        if (lineBuilder_ == null) {
          ensureLineIsMutable();
          line_.add(builderForValue.build());
          onChanged();
        } else {
          lineBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Line line = 1;</code>
       */
      public Builder addLine(
          int index, Line.Builder builderForValue) {
        if (lineBuilder_ == null) {
          ensureLineIsMutable();
          line_.add(index, builderForValue.build());
          onChanged();
        } else {
          lineBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Line line = 1;</code>
       */
      public Builder addAllLine(
          Iterable<? extends Line> values) {
        if (lineBuilder_ == null) {
          ensureLineIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, line_);
          onChanged();
        } else {
          lineBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Line line = 1;</code>
       */
      public Builder clearLine() {
        if (lineBuilder_ == null) {
          line_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          lineBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Line line = 1;</code>
       */
      public Builder removeLine(int index) {
        if (lineBuilder_ == null) {
          ensureLineIsMutable();
          line_.remove(index);
          onChanged();
        } else {
          lineBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Line line = 1;</code>
       */
      public Line.Builder getLineBuilder(
          int index) {
        return getLineFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Line line = 1;</code>
       */
      public LineOrBuilder getLineOrBuilder(
          int index) {
        if (lineBuilder_ == null) {
          return line_.get(index);  } else {
          return lineBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Line line = 1;</code>
       */
      public java.util.List<? extends LineOrBuilder>
           getLineOrBuilderList() {
        if (lineBuilder_ != null) {
          return lineBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(line_);
        }
      }
      /**
       * <code>repeated .Line line = 1;</code>
       */
      public Line.Builder addLineBuilder() {
        return getLineFieldBuilder().addBuilder(
            Line.getDefaultInstance());
      }
      /**
       * <code>repeated .Line line = 1;</code>
       */
      public Line.Builder addLineBuilder(
          int index) {
        return getLineFieldBuilder().addBuilder(
            index, Line.getDefaultInstance());
      }
      /**
       * <code>repeated .Line line = 1;</code>
       */
      public java.util.List<Line.Builder>
           getLineBuilderList() {
        return getLineFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Line, Line.Builder, LineOrBuilder>
          getLineFieldBuilder() {
        if (lineBuilder_ == null) {
          lineBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Line, Line.Builder, LineOrBuilder>(
                  line_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          line_ = null;
        }
        return lineBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Lines)
    }

    // @@protoc_insertion_point(class_scope:Lines)
    private static final Lines DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Lines();
    }

    public static Lines getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Lines>
        PARSER = new com.google.protobuf.AbstractParser<Lines>() {
      public Lines parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Lines(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Lines> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Lines> getParserForType() {
      return PARSER;
    }

    public Lines getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Point_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Point_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Line_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Line_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Lines_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Lines_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013Lines.proto\"\035\n\005Point\022\t\n\001x\030\001 \002(\002\022\t\n\001y\030\002" +
      " \002(\002\"u\n\004Line\022\r\n\005width\030\001 \002(\002\022\025\n\005start\030\002 \002" +
      "(\0132\006.Point\022\025\n\005point\030\003 \003(\0132\006.Point\022\023\n\003end" +
      "\030\004 \002(\0132\006.Point\022\r\n\005color\030\005 \002(\005\022\014\n\004type\030\006 " +
      "\002(\005\"\034\n\005Lines\022\023\n\004line\030\001 \003(\0132\005.LineB\014B\nLin" +
      "esProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Point_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Point_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Point_descriptor,
        new String[] { "X", "Y", });
    internal_static_Line_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Line_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Line_descriptor,
        new String[] { "Width", "Start", "Point", "End", "Color", "Type", });
    internal_static_Lines_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Lines_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Lines_descriptor,
        new String[] { "Line", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
